import { createHash } from "node:crypto";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = fileURLToPath(new URL("..", import.meta.url));
const sourceRoots = ["src", "index.html", "public/site.webmanifest", "public/pwa-icon.svg", "public/offline.html"];

async function collectFiles(target) {
  const fullPath = join(webRoot, target);
  const entries = await readdir(fullPath, { withFileTypes: true }).catch(() => null);
  if (!entries) return [fullPath];
  return (await Promise.all(entries.map(async (entry) => entry.isDirectory()
    ? collectFiles(relative(webRoot, join(fullPath, entry.name)))
    : [join(fullPath, entry.name)]))).flat();
}

const files = (await Promise.all(sourceRoots.map(collectFiles))).flat().sort();
const version = createHash("sha256");
for (const file of files) version.update(await readFile(file));
const buildId = version.digest("hex").slice(0, 12);

const worker = `/* Generated by scripts/prepare-pwa.mjs. */
const CACHE_NAME = "uhd-offline-${buildId}";
const OFFLINE_URL = "/offline.html";

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.add(OFFLINE_URL)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys
    .filter((key) => key.startsWith("uhd-offline-") && key !== CACHE_NAME)
    .map((key) => caches.delete(key)))).then(() => self.clients.claim()));
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  if (event.request.mode !== "navigate") return;
  event.respondWith(fetch(event.request).catch(() => caches.match(OFFLINE_URL)));
});
`;

await writeFile(join(webRoot, "public/sw.js"), worker);
console.log(`Prepared PWA service worker (${buildId}).`);
